#!/usr/bin/env python3
"""Validate corpus V1 and export independent JSONL inputs for local LCE runs.

No embeddings or semantic ground truth is generated by this script.
"""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
ARMS = ("baseline", "attribution", "state")
TRACKS = ("release", "jewelry", "venue", "scanners")


def sha256(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--out", type=Path, default=Path("lce_corpus_exports_v1"))
    args = p.parse_args()
    data = json.loads((ROOT / "fixed_blocks.json").read_text(encoding="utf-8"))
    cases = data["cases"]
    assert data["synthetic_only"] is True
    assert len(cases) == 24, "corpus size changed"
    assert data["arms"] == list(ARMS)
    ids = [c["block_id"] for c in cases]
    assert len(set(ids)) == len(ids), "duplicate block ID"
    for track in TRACKS:
        subset = [c for c in cases if c["track"] == track]
        assert len(subset) == 6, (track, len(subset))
        assert [c["known_at"] for c in subset] == sorted(c["known_at"] for c in subset)
    for c in cases:
        assert len(c["source_turns"]) > 0
        assert {t["role"] for t in c["source_turns"]} <= {"user", "assistant"}
        assert all(c["compiled"].get(a, "").strip() for a in ARMS)
        assert len({x["turn_id"] for x in c["source_turns"]}) == len(c["source_turns"])
        assert all(ref in ids for ref in c["prior_context_ids"])
    args.out.mkdir(parents=True, exist_ok=True)
    files = {}
    for arm in ARMS:
        out_file = args.out / f"{arm}.jsonl"
        with out_file.open("w", encoding="utf-8") as out:
            for c in cases:
                row = {
                    "id": c["block_id"],
                    "text": c["compiled"][arm],
                    "known_at": c["known_at"],
                    "track": c["track"]
                }
                out.write(json.dumps(row, ensure_ascii=False) + "\n")
        files[arm] = {"sha256": sha256(out_file), "records": len(cases), "file": out_file.name}
    manifest = {
        "source_file_sha256": sha256(ROOT / "fixed_blocks.json"),
        "independent_arms": files,
        "manual_synthetic_compilations": True,
        "real_lce_model_used": False,
        "llm_semantic_judgments_run": False
    }
    (args.out / "EXPORT_RECEIPT.json").write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print("PASS: 24 fixed blocks, 4x6 event tracks, 72 manual compilations, 3 independent LCE arm files")
    for arm, info in files.items():
        print(f"{arm}: {info['file']} 24 rows sha256={info['sha256']}")
    print(f"Saved: {args.out / 'EXPORT_RECEIPT.json'}")


if __name__ == "__main__":
    main()
